# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18V-kZejn371M0HllPjg82J5UYzC0298r
"""

import pandas as pd

# Load Financial Data
df = pd.read_csv("BCG.csv")


# 2. Clean Financial Data
metrics = [
    "Total Revenue",
    "Net Income",
    "Total Assets",
    "Total Liabilities",
    "Operating Cash Flow"
]

# Remove commas and convert each metric to numeric
for metric in metrics:
    df[metric] = (
        df[metric]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    df[metric] = pd.to_numeric(df[metric], errors="coerce")

# Ensure Fiscal Year is numeric
df["Fiscal Year"] = pd.to_numeric(df["Fiscal Year"], errors="coerce")

# Sort data by Company and Fiscal Year for logical ordering
df = df.sort_values(["Company", "Fiscal Year"]).reset_index(drop=True)


# Rule-Based Chatbot Function
def simple_chatbot(user_query):

    # Normalize input for easier matching
    query = user_query.lower().strip()

    # Identify the company from the query
    if "microsoft" in query:
        company = "Microsoft"
    elif "tesla" in query:
        company = "Tesla"
    elif "apple" in query:
        company = "Apple"
    else:
        company = None

    # Identify the year from the query
    if "2023" in query:
        year = 2023
    elif "2024" in query:
        year = 2024
    elif "2025" in query:
        year = 2025
    else:
        year = 2025  # default to most recent year

    # Error handling: no company specified
    if company is None:
        return (
            "Please specify a company: Microsoft, Tesla, or Apple. "
            "For example: 'What is Microsoft's total revenue in 2025?'"
        )

    # Query Type 1: Net Income Change (must be checked FIRST)
    if "net income" in query and (
        "change" in query
        or "changed" in query
        or "growth" in query
        or "increase" in query
        or "decrease" in query
    ):
        try:
            company_data = df[df["Company"] == company].sort_values("Fiscal Year")

            income_2024 = company_data[
                company_data["Fiscal Year"] == 2024
            ]["Net Income"].iloc[0]

            income_2025 = company_data[
                company_data["Fiscal Year"] == 2025
            ]["Net Income"].iloc[0]

            percentage_change = (
                (income_2025 - income_2024) / income_2024
            ) * 100

            if percentage_change >= 0:
                return (
                    f"{company}'s net income increased by "
                    f"{percentage_change:.2f}% from 2024 to 2025."
                )
            else:
                return (
                    f"{company}'s net income decreased by "
                    f"{abs(percentage_change):.2f}% from 2024 to 2025."
                )
        except IndexError:
            return f"Data for {company} is incomplete (needs both 2024 and 2025)."

    # Query Type 2: Total Revenue
    elif "revenue" in query:
        result = df[
            (df["Company"] == company) & (df["Fiscal Year"] == year)
        ]
        if not result.empty:
            revenue = result.iloc[0]["Total Revenue"]
            return (
                f"{company}'s total revenue in {year} "
                f"was ${revenue:,.0f} million."
            )
        return f"Sorry, I couldn't find revenue data for {company} in {year}."

    # Query Type 3: Net Income (simple value)
    elif "net income" in query:
        result = df[
            (df["Company"] == company) & (df["Fiscal Year"] == year)
        ]
        if not result.empty:
            income = result.iloc[0]["Net Income"]
            return (
                f"{company}'s net income in {year} "
                f"was ${income:,.0f} million."
            )
        return f"Sorry, I couldn't find net income data for {company} in {year}."

    # Query Type 4: Operating Cash Flow
    elif "operating cash flow" in query or "cash flow" in query:
        result = df[
            (df["Company"] == company) & (df["Fiscal Year"] == year)
        ]
        if not result.empty:
            cash_flow = result.iloc[0]["Operating Cash Flow"]
            return (
                f"{company}'s operating cash flow in {year} "
                f"was ${cash_flow:,.0f} million."
            )
        return f"Sorry, I couldn't find cash flow data for {company} in {year}."

    # Query Type 5: Total Assets
    elif "assets" in query or "total assets" in query:
        result = df[
            (df["Company"] == company) & (df["Fiscal Year"] == year)
        ]
        if not result.empty:
            assets = result.iloc[0]["Total Assets"]
            return (
                f"{company}'s total assets in {year} "
                f"were ${assets:,.0f} million."
            )
        return f"Sorry, I couldn't find asset data for {company} in {year}."

    # Query Type 6: Total Liabilities
    elif "liabilities" in query:
        result = df[
            (df["Company"] == company) & (df["Fiscal Year"] == year)
        ]
        if not result.empty:
            liabilities = result.iloc[0]["Total Liabilities"]
            return (
                f"{company}'s total liabilities in {year} "
                f"were ${liabilities:,.0f} million."
            )
        return f"Sorry, I couldn't find liability data for {company} in {year}."

    # Fallback: unrecognized query
    else:
        return (
            "Sorry, I don't understand that query. "
            "I can answer questions about total revenue, "
            "net income, net income changes, total assets, "
            "total liabilities, and operating cash flow "
            "for Microsoft, Tesla, and Apple."
        )


# 4. Interactive Chatbot Loop
if __name__ == "__main__":

    print("GFC FINANCIAL CHATBOT")
    print("Rule-Based Financial Analysis Prototype")

    print("\nYou can ask questions such as:")
    print("  1. What is Microsoft's total revenue in 2025?")
    print("  2. What is Tesla's net income in 2025?")
    print("  3. How has Apple's net income changed?")
    print("  4. What is Microsoft's operating cash flow in 2025?")
    print("  5. What are Tesla's total assets in 2025?")
    print("  6. What are Apple's total liabilities in 2024?")
    print("\nType 'exit' to stop the chatbot.\n")

    while True:
        user_query = input("You: ")

        if user_query.lower().strip() == "exit":
            print("Chatbot: Thank you for using the GFC Financial Chatbot.")
            break

        response = simple_chatbot(user_query)
        print("Chatbot:", response)

# Chatbot Test Harness

test_queries = [
    # Valid queries
    "What is Microsoft's total revenue in 2025?",
    "What is Tesla's net income in 2025?",
    "How has Apple's net income changed?",
    "What is Microsoft's operating cash flow in 2025?",
    "What are Tesla's total assets in 2025?",
    "What are Apple's total liabilities in 2024?",
    "How has Tesla's net income changed?",
    "What is Apple's revenue in 2023?",
    "What is Microsoft's total assets in 2024?",

    # Error / fallback cases
    "What is Google's revenue in 2025?",          # Unknown company
    "Tell me about profits",                       # Unknown intent
    "What is revenue?",                            # No company specified
]

print("CHATBOT - TEST RESULTS")

for q in test_queries:
    print(f"\nYou: {q}")
    response = simple_chatbot(q)
    print(f"Chatbot: {response}")